import { strict as assert } from 'node:assert';
import { ROLE, DEFAULT_SETTINGS, calculateSales, calculateCashEquation, calculateBeerAllocation, calculateCompensationMonth, calculateDashboard } from './calc.js';
const tests=[];const test=(name,fn)=>tests.push({name,fn});

test('ยอดขายรวมและรายได้รวม',()=>{const r=calculateSales({foodCents:100000,beverageCents:50000,discountCents:10000,cashCents:80000,transferCents:60000});assert.equal(r.grossSalesCents,150000);assert.equal(r.revenueCents,140000);assert.equal(r.paymentDifferenceCents,0);});
test('สมการเงินสดตรง',()=>{const r=calculateCashEquation({openingCashCents:10000,cashSalesCents:50000,shiftExpenses:[{amountCents:5000,ownerPaid:false},{amountCents:7000,ownerPaid:true}],cashToOwnerCents:20000,closingCashCents:35000});assert.equal(r.expectedClosingCents,35000);assert.equal(r.status,'balanced');});
test('สมการเงินสดขาดและเกิน',()=>{assert.equal(calculateCashEquation({openingCashCents:10000,cashSalesCents:10000,closingCashCents:19000}).status,'short');assert.equal(calculateCashEquation({openingCashCents:10000,cashSalesCents:10000,closingCashCents:21000}).status,'over');});
test('Draft ไม่เข้า Dashboard',()=>{const r=calculateDashboard({sales:[{status:'draft',storeStatus:'open',revenueCents:999999},{status:'final',storeStatus:'open',revenueCents:10000,shiftExpenses:[],cashToOwnerCents:0}],grossMarginRate:1});assert.equal(r.revenueCents,10000);});
test('โบนัสรายวันครัวและรายเดือน',()=>{const users=[{id:'k',displayName:'ครัว',role:ROLE.FRONT_KITCHEN}];const attendance=[{userId:'k',date:'2026-07-01',role:ROLE.FRONT_KITCHEN,status:'full_day'}];const sales=[{date:'2026-07-01',status:'final',storeStatus:'open',foodCents:10000001,beverageCents:0,beerBottles:0}];const r=calculateCompensationMonth({users,attendance,sales,settings:DEFAULT_SETTINGS});assert.equal(r.records[0].dailyBonusCents,10000);assert.equal(r.records[0].monthlyBonusCents,100000);});
test('โบนัสรายวันหน้าร้าน',()=>{const users=[{id:'f',displayName:'หน้า',role:ROLE.FRONT_STAFF}];const attendance=[{userId:'f',date:'2026-07-01',role:ROLE.FRONT_STAFF,status:'full_day'}];const sales=[{date:'2026-07-01',status:'final',storeStatus:'open',foodCents:0,beverageCents:1000001,beerBottles:0}];const r=calculateCompensationMonth({users,attendance,sales,settings:DEFAULT_SETTINGS});assert.equal(r.records[0].dailyBonusCents,10000);});
test('โบนัสเบียร์หารลงตัว',()=>{const a=[{userId:'a',date:'2026-07-01',role:ROLE.FRONT_STAFF,status:'full_day'},{userId:'b',date:'2026-07-01',role:ROLE.DAILY,status:'full_day'}];const s=[{date:'2026-07-01',status:'final',storeStatus:'open',beerBottles:2}];const r=calculateBeerAllocation({sales:s,attendance:a,settings:{...DEFAULT_SETTINGS,beerRateCents:500}});assert.equal(r.byUser.a,500);assert.equal(r.byUser.b,500);});
test('โบนัสเบียร์หารไม่ลงตัวรวมไม่เกินยอด',()=>{const a=['a','b','c'].map(userId=>({userId,date:'2026-07-01',role:ROLE.FRONT_STAFF,status:'full_day'}));const s=[{date:'2026-07-01',status:'final',storeStatus:'open',beerBottles:1}];const r=calculateBeerAllocation({sales:s,attendance:a,settings:{...DEFAULT_SETTINGS,beerRateCents:500}});assert.equal(Object.values(r.byUser).reduce((x,y)=>x+y,0),500);assert.deepEqual(Object.values(r.byUser).sort((x,y)=>x-y),[166,167,167]);});
test('พนักงานเวียน Love Matcha ไม่รับโบนัส Rendo ตามค่าเริ่มต้น',()=>{const a=[{userId:'r',date:'2026-07-01',role:ROLE.ROTATING_STAFF,status:'full_day',workLocation:'Love Matcha'}];const s=[{date:'2026-07-01',status:'final',storeStatus:'open',beverageCents:2000000,beerBottles:10}];const r=calculateCompensationMonth({users:[{id:'r',displayName:'เวียน',role:ROLE.ROTATING_STAFF}],attendance:a,sales:s,settings:DEFAULT_SETTINGS});assert.equal(r.records[0].dailyBonusCents,0);assert.equal(r.records[0].beerBonusCents,0);});
test('รายวันทั้งวัน รายชั่วโมง และจ่ายแล้ว',()=>{const users=[{id:'d',displayName:'รายวัน',role:ROLE.DAILY}];const attendance=[{id:'1',userId:'d',date:'2026-07-01',role:ROLE.DAILY,status:'full_day',paid:true},{id:'2',userId:'d',date:'2026-07-02',role:ROLE.DAILY,status:'hourly',startMinutes:660,endMinutes:900,paid:false}];const profiles={d:{dailyFullDayRateCents:50000,dailyHourlyRateCents:6000,socialSecurityEnabled:false}};const r=calculateCompensationMonth({users,profiles,attendance,settings:DEFAULT_SETTINGS}).records[0];assert.equal(r.allDailyWagesCents,74000);assert.equal(r.paidDailyWagesCents,50000);assert.equal(r.unpaidDailyWagesCents,24000);assert.equal(r.transferCents,24000);assert.equal(r.shopCostCents,74000);});
test('เงินเบิกล่วงหน้าไม่ลดต้นทุนซ้ำ',()=>{const users=[{id:'f',displayName:'หน้า',role:ROLE.FRONT_STAFF}];const profiles={f:{baseSalaryCents:1000000,socialSecurityEnabled:false}};const advances=[{userId:'f',amountCents:20000}];const r=calculateCompensationMonth({users,profiles,advances,settings:DEFAULT_SETTINGS}).records[0];assert.equal(r.transferCents,980000);assert.equal(r.shopCostCents,1000000);});
test('ประกันสังคมต่ำกว่าเพดานและชนเพดาน',()=>{const users=[{id:'a',displayName:'A',role:ROLE.FRONT_STAFF},{id:'b',displayName:'B',role:ROLE.FRONT_STAFF}];const profiles={a:{baseSalaryCents:1000000,socialSecurityEnabled:true},b:{baseSalaryCents:2000000,socialSecurityEnabled:true}};const r=calculateCompensationMonth({users,profiles,settings:{...DEFAULT_SETTINGS,socialSecurityWageCeilingCents:1500000,socialSecurityEmployeeRate:.05,socialSecurityEmployerRate:.05}}).records;assert.equal(r.find(x=>x.userId==='a').employeeSocialSecurityCents,50000);assert.equal(r.find(x=>x.userId==='b').employeeSocialSecurityCents,75000);});
test('ยอดโอนและต้นทุนร้านตามสูตร',()=>{const users=[{id:'f',displayName:'หน้า',role:ROLE.FRONT_STAFF}];const profiles={f:{baseSalaryCents:1000000,socialSecurityEnabled:false}};const recordDrafts={f:{additionsCents:10000,outsideOtCents:5000,deductionsCents:3000}};const r=calculateCompensationMonth({users,profiles,recordDrafts,settings:DEFAULT_SETTINGS}).records[0];assert.equal(r.transferCents,1012000);assert.equal(r.shopCostCents,1012000);});
test('Dashboard ช่วงข้อมูลและสูตร 40%',()=>{const r=calculateDashboard({sales:[{status:'final',storeStatus:'open',revenueCents:100000,shiftExpenses:[{amountCents:10000}],cashToOwnerCents:5000}],ownerExpenses:[{amountCents:5000}],recurringExpenses:[],compensationRecords:[],grossMarginRate:.4});assert.equal(r.estimatedAfterProductCostCents,40000);assert.equal(r.afterExpensesCents,25000);});

let passed=0;for(const t of tests){try{await t.fn();console.log(`PASS ${t.name}`);passed++;}catch(e){console.error(`FAIL ${t.name}`,e);process.exitCode=1;}}console.log(`\n${passed}/${tests.length} tests passed`);
